name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generateReleaseNotes: true

  build-windows:
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables
        run: |
          python setup_cx.py build

      - name: Prepare artifacts
        run: |
          mkdir dist
          Copy-Item -Path "build\exe.*\*" -Destination dist -Recurse

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-cli
          path: dist/image_processor.exe

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-gui
          path: dist/image_processor_gui.exe

  build-macos:
    needs: create-release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables
        run: |
          python setup_cx.py build

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp -R build/exe.*/* dist/

      - name: List build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Exe directory contents:"
          ls -la build/exe.*
          echo "Dist directory contents:"
          ls -la dist/

      - name: Fix executable permissions
        run: |
          chmod +x dist/image_processor || echo "CLI executable not found"
          chmod +x dist/image_processor_gui || echo "GUI executable not found"

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-cli
          path: dist/image_processor

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-gui
          path: dist/image_processor_gui

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build CLI executable
        run: |
          python setup_cx.py build

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp -r build/exe.*/* dist/

      - name: Fix executable permissions
        run: |
          chmod +x dist/image_processor || echo "CLI executable not found"

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-cli
          path: dist/image_processor

  upload-release-assets:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Windows CLI
        uses: actions/download-artifact@v4
        with:
          name: windows-cli

      - name: Download Windows GUI
        uses: actions/download-artifact@v4
        with:
          name: windows-gui

      - name: Download macOS CLI
        uses: actions/download-artifact@v4
        with:
          name: macos-cli

      - name: Download macOS GUI
        uses: actions/download-artifact@v4
        with:
          name: macos-gui

      - name: Download Linux CLI
        uses: actions/download-artifact@v4
        with:
          name: linux-cli

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "*"
          token: ${{ secrets.GITHUB_TOKEN }}