name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generateReleaseNotes: true

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build CLI executable
        run: |
          pyinstaller --onefile image_processor.py

      - name: Build GUI executable
        run: |
          pyinstaller --onefile --windowed image_processor_gui.py

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-cli
          path: dist/image_processor.exe

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-gui
          path: dist/image_processor_gui.exe

  build-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build CLI executable
        run: |
          pyinstaller --onefile image_processor.py

      - name: Build GUI executable
        run: |
          pyinstaller --onefile --windowed image_processor_gui.py

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-cli
          path: dist/image_processor

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-gui
          path: dist/image_processor_gui.app

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build CLI executable
        run: |
          pyinstaller --onefile image_processor.py

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-cli
          path: dist/image_processor

  upload-release-assets:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows CLI
        uses: actions/download-artifact@v3
        with:
          name: windows-cli

      - name: Download Windows GUI
        uses: actions/download-artifact@v3
        with:
          name: windows-gui

      - name: Download macOS CLI
        uses: actions/download-artifact@v3
        with:
          name: macos-cli

      - name: Download macOS GUI
        uses: actions/download-artifact@v3
        with:
          name: macos-gui

      - name: Download Linux CLI
        uses: actions/download-artifact@v3
        with:
          name: linux-cli

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "./*"
          token: ${{ secrets.GITHUB_TOKEN }}